apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivia-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivia-fe
  template:
    metadata:
      labels:
        app: trivia-fe
    spec:
      containers:
        - name: trivia-fe
          image: gcr.io/vpn-gcp-411410/trivia-fe/v1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: trivia-fe-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: trivia-fe
